version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: firebase-admin
    versions:
    - 9.4.2
    - 9.5.0
    - 9.6.0
  - dependency-name: dompurify
    versions:
    - 2.2.6
    - 2.2.7
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  - dependency-name: highcharts
    versions:
    - 9.0.0
  - dependency-name: "@types/faker"
    versions:
    - 5.1.5
  - dependency-name: highcharts-angular
    versions:
    - 2.9.0
